name: tests

on:
  push:
  pull_request:

jobs:
  pytest:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]
    env:
      PYTHONPATH: ${{ github.workspace }}   # <- Κάνει importable το 'core', 'features', κλπ
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        working-directory: ${{ github.workspace }}   # <- τρέχει από τη ρίζα του repo
        run: python -m pytest -q
